### ISSUE TITLE
Make Hosted Weblate point to the new repository

### ISSUE THREAD

**Issue by ryonakano** [elementary-community/sequeler#390]
### What Happened?
Sequeler seems to use Hosted Weblate and it points to the old repository URL, https://github.com/Alecaddd/sequeler. This is problematic because maybe Weblate can't push to the new repository.

### Steps to Reproduce
1. Visit [Hosted Weblate](https://hosted.weblate.org/projects/sequeler/translations/#information)
2. See the `Project website` and `Source code repository` point to the old repository URL:

![Screenshot from 2024-09-24 07-17-34](https://github.com/user-attachments/assets/25bb7903-ff10-4b48-a79f-daf459a1b86f)

### Expected Behavior
It points to the new repository, https://github.com/elementary-community/sequeler.

**Comment by Alecaddd** [comment]
Thanks for the ping, will update this!

**Comment by Alecaddd** [comment]
@ryonakano I updated the git repo in a few spots but I see that there are a lot of options.
Since I don't have a lot of free time I made you ad admin so feel free to change things as needed.

**Comment by ryonakano** [comment]
@Alecaddd Thank you for invitation. I updated the `Project website` URL in the above screenshot and `Repository push URL` in the [VCS settings page](https://hosted.weblate.org/settings/sequeler/translations/#vcs). I confirmed Weblate can push to this repository (692897a9b03f172fef2c158dfe0b65667d784e08), so closing as completed!
